# MySQL installation for WordPress
- name: Install python3-pip
  ansible.builtin.apt:
    name:
      - python3-pip
    update_cache: yes

- name: Install pymysql for community.mysql plugin
  ansible.builtin.pip:
    name: pymysql
    break_system_packages: yes

- name: Create database in MySQL
  community.mysql.mysql_db:
    login_host: "{{ wordpress_database_host }}"
    login_user: "{{ mysql_user_username }}"
    login_password: "{{ mysql_user_password }}"
    name: wordpress
    state: present

- name: Create database wordpress user
  community.mysql.mysql_user:
    login_host: "{{ wordpress_database_host }}"
    login_user: "{{ mysql_user_username }}"
    login_password: "{{ mysql_user_password }}"
    name: wordpress
    password: "{{ wordpress_database_password }}"
    priv: 'wordpress.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER'
    host: "{{ ansible_host }}"
    state: present