win:
  children:
    win_dc:
      hosts:
        win2022-svr01:
          ansible_host: 192.168.10.135
          host_name: WIN-SVR01
      vars:
        ansible_user: Administrator
        ansible_password: P@ssw0rd
    win_arc:
      hosts:
        win2022-svr02:
          ansible_host: 192.168.10.140
          host_name: WIN-SVR02
      vars:
        ansible_user: Administrator
        ansible_password: P@ssw0rd
        azure:
          service_principal_id: ''
          service_principal_secret: ''
          resource_group: ''
          tenant_id: ''
          subscription_id: ''
          location: ''
    win_pc:
      hosts:
        win11-pc01:
          ansible_host: 192.168.10.139
          host_name: WIN-PC01
      vars:
        ansible_user: Admin
        ansible_password: P@ssw0rd

ubuntu:
  children:
    ubuntu_arc:
      hosts:
        ubuntu24.04.3-svr01:
          ansible_host: 192.168.10.147
          ansible_user: ubuntu
          host_name: ubuntu-svr01
      vars:
        ansible_become_password: P@ssw0rd
        azure:
          service_principal_id: ''
          service_principal_secret: ''
          resource_group: ''
          tenant_id: '7'
          subscription_id: ''
          location: ''
    ubuntu_mysql:
      hosts:
        ubuntu24.04.3-svr02:
          ansible_host: 192.168.10.146
          ansible_user: ubuntu
          host_name: ubuntu-svr02
      vars:
        ansible_become_password: P@ssw0rd
        mysql_root_password: P@ssw0rd
        mysql_user_username: admin
        mysql_user_password: P@ssw0rd
    ubuntu_wordpress:
      hosts:
        ubuntu24.04.3-svr03:
          ansible_host: 192.168.10.145
          ansible_user: ubuntu
          host_name: ubuntu-svr03
      vars:
        ansible_become_password: P@ssw0rd
        mysql_user_username: "{{ hostvars[mysql_server]['mysql_user_username'] }}"
        mysql_user_password: "{{ hostvars[mysql_server]['mysql_user_password'] }}"
        wordpress_database_host: "{{ hostvars[mysql_server]['ansible_host'] }}"
        wordpress_database_name: wordpress
        wordpress_database_username: wordpress
        wordpress_database_password: P@ssw0rd